### ISSUE TITLE
Nastylování tlačítek

### ISSUE THREAD

**Issue by matejkrenek** [Smartshopik/software-eshop#5]
### Úvod
- držíme se předlohy, kterou jsem ti ukazoval a na kterou je odkaz v `README.md` souboru tohoto projektu
### Co vše je třeba okolo tlačítek udělat
- dva styly: světlé a tmavé (primární) - tlačítka na obrázku můžeš vidět, když si klikneš na košík na webu:

![Image](https://github.com/Smartshopik/software-eshop/assets/64211833/d6e9a5ca-42af-49dd-a7de-a3ed3ec68f40)

- tři různé velikosti:
  - normální - stejná velikost jako velikost tlačítek na webu
  - malá velikost - trošku menší paddingy a velikost písma
  - velká velikost - trošku větší paddingy a velikost písma
- hover, focus a active stavy na tlačítkách
  - nezapoměň nastylovat tyto stavy (:hover, :active, :focus)
- loading a disabled stavy
  - při disabled stavu je tlačíku trošku méně viditelné nebo zašedlé (prostě aby uživatel věděl, že je vypnuté) a nedá se na něj klikat
     - tento stav se na tlačítku nastaví pomocí `is-disabled` classy nebo přidáním `disabled` html attributu
  - při loading stavu se na tlačíko nedá klikat a na tlačíku se točí kolečko
     - tento stav se na tlačítko nastaví pomocí `is-loading` classy
- tlačíka s ikonkoma
  - ještě se může stát, že bude potřeba tlačítko s ikonkou, takže to taky nastyluj (to jaké ikonky používáme je zase napsané v README.md souboru)
  - tlačítko může mít ikonku vpravo od textu, vlevo od textu, a nebo může být kompletně bez textu pouze s ikonkou
 ### Pojmenovávání class
- každé tlačítko bude mít `btn` classu
- následné modifikátory tlačítka se přidávájí přidáním dalších class
  - `btn--sm` - malá velikost tlačíka
  - `btn--lg` - velká velikost tlačítka
- příklad celého tlačíka:
```html
<a href="" class="btn">Tlačítko</a> -> normální priamry fialové tlačítko
<a href="" class="btn btn--sm">Tlačítko</a> -> normální primary fialové tlačítko menší velikosti
<a href="" class="btn btn--secondary">Tlačítko</a> -> světlé tlačíko normální velikost
<a href="" class="btn is-disabled">Tlačítko</a> -> normání tlačítko fialové ve stavu disabled pomocí is-disabled classy
<button type="button" class="btn" disabled>Tlačítko</a> -> normální primary fialové tlačítko ve stavu disabled pomocí disabled html attributu
```
 ### Inspirace
- můžeš se inspirovat v tom `autima` projektu, který jsem ti ukazoval, tam všechny tyto věci ohledně tlačítek jsou hotové akorát změníš barvičky a velikost a border-radiusy

**Comment by Terezkamaz** [comment]
nejde mi otevřít img, píše mi to access denied
